[project]
name = "nanochat"
version = "0.1.0"
dependencies = [
    "jax[tpu]",
    "flax",
    "optax",
    "orbax-checkpoint",
    "grain-nightly",
    "pyarrow",
    "requests",
    "tiktoken",
    "tokenizers",
    "psutil",
    "pytest",
    "tokamax",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
